apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 10m
  path: "./kustomize/linkerd/"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flagger
