---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./common/loki-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
