apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/fluxcd/flagger
  ref:
    tag: v1.12.1
  ignore: |
    /*
    !/kustomize
