---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: treats-portfolio
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: treats-portfolio
  filterTags:
    pattern: "test"
  # policy:
  #   semver:
  #     # range: ">=8.0.0-develop"
  #     range: "test"
