---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd
  interval: 1h
  path: ./common/flagger
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  validation: client
