---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: grafana-agent
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./monitoring/grafana-agent
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: monitoring
  validation: client
