# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: linkerd
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: namespaces
#   healthChecks:
#     - kind: Deployment
#       name: linkerd-proxy-injector
#       namespace: linkerd
#   interval: 1m0s
#   path: ./common/linkerd
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   timeout: 2m0s
#   validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  healthChecks:
    - kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd
  interval: 30m0s
  path: ./common/linkerd-nohelm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client
