---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: grafana-agent
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    branch: main
  url: https://github.com/grafana/agent
