---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 7.6.21
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
  interval: 24h
  targetNamespace: nginx
  values:
    podAnnotations:
      linkerd.io/inject: enabled
    image:
      registry: docker.io
      repository: bitnami/nginx-ingress-controller
      tag: 0.48.1-debian-10-r49
