---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: loki-stack
  targetNamespace: loki
  values:
    grafana:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - grafana.k8s.local
      plugins:
        - grafana-worldmap-panel
