---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: loki-stack
  targetNamespace: loki
  values:
    filebeat:
      enabled: false
      filebeatConfig:
        filebeat.yml: |
          # logging.level: debug
          filebeat.inputs:
          - type: container
            paths:
              - /var/log/containers/*.log
            processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
          output.logstash:
            hosts: ["loki-stack-logstash-headless:9600"]
    logstash:
      enabled: false
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - grafana.k8s.local
      plugins:
        - grafana-worldmap-panel
      persistence:
        enabled: true
