apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: loki
  namespace: loki
spec:
  rules:
    - host: loki.k8s.local
      http:
        paths:
          - backend:
              serviceName: loki
              servicePort: 3100
