---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      version: 5.9.2
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
  interval: 10m0s
  targetNamespace: metrics-server
  values:
    apiService:
      create: true
    extraArgs:
      kubelet-insecure-tls: true
      kubelet-preferred-address-types: InternalIP
