---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frog-dogs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: frog-docs
      sourceRef:
        kind: HelmRepository
        name: stiforr
  install: {}
  interval: 30m0s
  values:
    ingress:
      enabled: true
      className: ""
      annotations:
        kubernetes.io/ingress.class: nginx
      tls: {}
