---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frog-docs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/frog-docs
      sourceRef:
        kind: GitRepository
        name: flux-system
  install: {}
  interval: 1m0s
  targetNamespace: default
