---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install: {}
  interval: 1m0s
  targetNamespace: default
  values:
    ghostUsername: stiforr
    ghostPassword: password12345
    allowEmptyPassword: false
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: ghost.k8s.local
    mariadb:
      auth:
        rootPassword: "password"
        password: "password"
