---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mealie
      sourceRef:
        kind: HelmRepository
        name: truecharts
  install: {}
  interval: 30m0s
  targetNamespace: default
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: mealie.k8s.local
            paths:
              path: /
