---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rocketchat
      sourceRef:
        kind: HelmRepository
        name: rocketchat
  install: {}
  interval: 30m0s
  targetNamespace: default
  values:
    ingress:
      enabled: true
      hosts:
        - chat.k8s.local
    mongodb:
      auth:
        password: password
        username: rocketchat
        rootPassword: password
        database: rocketchat
