---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: suitecrm
  namespace: flux-system
spec:
  chart:
    spec:
      chart: suitecrm
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install: {}
  interval: 1m0s
  targetNamespace: default
  values:
    suitecrmHost: "crm.k8s.local"
    suitecrmUsername: "stiforr"
    suitecrmPassword: "password"
    mariadb:
      auth:
        rootPassword: "password"
        password: "password"
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: crm.k8s.local
