apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: treats-portfolio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: treats-portfolio
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: stiforr
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  interval: 24h
  targetNamespace: default
  values:
    image:
      tag: 8.4.0-test # {"$imagepolicy": "flux-system:treats-portfolio:tag"}
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
          grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      hosts:
        - host: treats.k8s.local
          paths:
            - path: /
              pathType: ImplementationSpecific
    flagger:
      enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
