---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: treats-portfolio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: treats-portfolio
      sourceRef:
        kind: HelmRepository
        name: stiforr
  install: {}
  interval: 10m0s
  targetNamespace: default
  values:
    image:
      tag: 8.4.0-develop.14 # {"$imagepolicy": "flux-system:treats-portfolio:tag"}
