---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install: {}
  interval: 1m0s
  targetNamespace: default
  values:
    wordpressUsername: stiforr
    wordpressPassword: password
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: wordpress.k8s.local
    service:
      type: ClusterIP
    mariadb:
      auth:
        rootPassword: "password"
        password: "password"
