---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
  install:
    createNamespace: false
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  interval: 1m0s
  targetNamespace: linkerd-viz
  values:
    grafanaUrl: "http://grafana.k8s.local"
    grafana:
      enabled: false
    prometheus:
      enabled: false
