---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd-viz
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: linkerd
  install:
    createNamespace: true
    remediation:
      retries: 20
  upgrade:
    remediation:
      retries: 20
  interval: 24h
  targetNamespace: linkerd-viz
  values:
    grafanaUrl: "http://kube-prometheus-stack-grafana.linkerd-viz.svc.cluster.local:3000"
    prometheusUrl: "http://kube-prometheus-stack-prometheus.linkerd-viz.svc.cluster.local:9090"
    grafana:
      enabled: false
    prometheus:
      enabled: false
    installNamespace: false
