---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  version: 2.10.2
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
  install:
    createNamespace: true
    remediation:
      retries: 20
  upgrade:
    remediation:
      retries: 20
  interval: 1m0s
  targetNamespace: linkerd-viz
  values:
    # grafanaUrl: "grafana:3000"
    # prometheusUrl: "prometheus:9090"
    grafana:
      enabled: true
    prometheus:
      enabled: true
    installNamespace: false
