{
 "title": "Linkerd Pod",
 "description": "Linkerd Pod, golden metrics per pod",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(process_start_time_seconds, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, deployment)"
    }
   },
   { "name": "inbound", "query": { "query": "" } },
   {
    "name": "outbound",
    "query": {
     "query": "label_values(request_total{namespace=\"$namespace\", deployment=\"$deployment\"}, dst_deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">po/$pod</span>\n</div>"
   }
  },
  {
   "title": "SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s])) / sum(irate(response_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "INBOUND PODS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\"}) by (namespace, pod))"
    }
   ]
  },
  {
   "title": "OUTBOUND PODS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}) by (namespace, dst_pod))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC</span>\n</div>"
   }
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s])) by (pod) / sum(irate(response_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\", tls=\"true\"}[30s])) by (pod)",
     "legendFormat": "🔒po/{{pod}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\", tls!=\"true\"}[30s])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s])) by (le, pod))",
     "legendFormat": "p50 po/{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s])) by (le, pod))",
     "legendFormat": "p95 po/{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"inbound\"}[30s])) by (le, pod))",
     "legendFormat": "p99 po/{{pod}}"
    }
   ]
  },
  {
   "title": "Inbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTIONS FAILURES",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", pod=\"$pod\" ,deployment=\"$deployment\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", pod=\"$pod\" ,deployment=\"$deployment\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", pod=\"$pod\" ,deployment=\"$deployment\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND PODS</span>\n</div>"
   }
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\"}[30s])) by (pod) / sum(irate(response_total{dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\"}[30s])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\", tls=\"true\"}[30s])) by (pod)",
     "legendFormat": "🔒po/{{pod}}"
    },
    {
     "expr": "sum(irate(request_total{dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\", tls!=\"true\"}[30s])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, pod))",
     "legendFormat": "p50 po/{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, pod))",
     "legendFormat": "p95 po/{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{dst_namespace=\"$namespace\", dst_pod!=\"\", dst_pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, pod))",
     "legendFormat": "p99 po/{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND TRAFFIC</span>\n</div>"
   }
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (pod) / sum(irate(response_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\", tls=\"true\"}[30s])) by (pod)",
     "legendFormat": "🔒po/{{pod}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\", tls!=\"true\"}[30s])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, pod))",
     "legendFormat": "p50 po/{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, pod))",
     "legendFormat": "p95 po/{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, pod))",
     "legendFormat": "p99 po/{{pod}}"
    }
   ]
  },
  {
   "title": "Outbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", pod=\"$pod\", deployment=\"$deployment\", direction=\"outbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", pod=\"$pod\" ,deployment=\"$deployment\", direction=\"outbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", deployment=\"$deployment\", direction=\"outbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND PODS</span>\n</div>"
   }
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (dst_pod) / sum(irate(response_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (dst_pod)",
     "legendFormat": "po/{{dst_pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_pod)",
     "legendFormat": "🔒po/{{dst_pod}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_pod)",
     "legendFormat": "po/{{dst_pod}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, dst_pod))",
     "legendFormat": "p50 po/{{dst_pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, dst_pod))",
     "legendFormat": "p95 po/{{dst_pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=\"$pod\", direction=\"outbound\"}[30s])) by (le, dst_pod))",
     "legendFormat": "p99 po/{{dst_pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>"
   }
  }
 ]
}